routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('panel');
});

Route::get('/prueba', function () {
    $user = Auth::user()->with('business')->with('business.entries')->first();
    return dd($user);
})->name('prueba');
Route::post('buscar', 'HomeController@buscar')->name('buscar');
Auth::routes(['register' => false]);

Route::prefix('panel')->group(function () {
    Route::get('/', 'HomeController@index')->name('panel');
    Route::get('account', 'HomeController@account')->name('settings');
    Route::post('changeuser/{user}', 'HomeController@changeuser')->name('changeuser');
    Route::post('changebiz/{business}', 'HomeController@changebiz')->name('changebiz');
    Route::resource('users', 'UserController');
    Route::resource('sales', 'SalesController');
    Route::resource('clients', 'ClientController');
    Route::resource('entries', 'EntryController');
    Route::resource('products', 'ProductsController');
    Route::resource('providers', 'ProvidersController');
    Route::resource('items', 'ProvidersItemController');
});

Route::prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('users', 'AdminController@userIndex')->name('admin.users.index');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['business_id', 'name', 'code', 'amount', 'price'];
    public function business()
    {
      return $this->belongsTo('App\Business');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Requestt;
use App\Product;
use Auth;
use Session;
use Illuminate\Http\Request;
class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct()
     {
         $this->middleware(['auth']);
     }
    public function index()
    {
        Session::flash('url',Requestt::server('HTTP_REFERER'));
        $products = Product::orderBy('id', 'desc')->get();
        return view('panel.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /*$subscription = Auth::user()->business->activeSubscription();
        if (Auth::user()->business->products->count() < $subscription->features()->code('products.amount')->first()->limit) {
            Session::flash('url',Requestt::server('HTTP_REFERER'));
            return view('panel.products.create');
        }
        else {
            return redirect()->back()->with('warning', 'Alcanzaste el limite de productos en tu plan.');
        }*/

        Session::flash('url',Requestt::server('HTTP_REFERER'));
        return view('panel.products.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'code' => 'required',
            'name' => 'required',
            'amount' => 'required|integer',
            'price' => 'required',
        ]);
        $product = new Product();
        $product->business_id = Auth::user()->business_id;
        $product->code = $request->code;
        $product->name = $request->name;
        $product->amount = $request->amount;
        $product->price = $request->price;
        if ($product->save()) {
          return redirect()->route('products.index')->with('message', 'Se ha creado un nuevo producto.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Session::flash('url',Requestt::server('HTTP_REFERER'));
        $product = Product::where('id', $id)->first();
        return view('panel.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      Session::flash('url',Requestt::server('HTTP_REFERER'));
      $product = Product::where('id', $id)->first();
      return view('panel.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'code' => 'required',
            'name' => 'required',
            'amount' => 'required|integer',
            'price' => 'required',
        ]);
      $product = Product::find($id);
      $product->code = $request->code;
      $product->name = $request->name;
      $product->amount = $request->amount;
      $product->price = $request->price;
      if ($product->save()) {
        return back()->with('message', 'Editaste el producto correctamente.');
      }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();
        return back();
    }
}

resources/views/panel/products/create.blade.php
@extends('panel.layouts.panel')
@section('content')
<br>
    <div class="row">
      <div class="col-lg-12">
        
        <div class="card card-outline-info">
            <div class="card-header">
                <h4 class="m-b-0 text-white text-center">Crear producto</h4>
            </div>
                <div class="card-body">
                    @include('vendor.errors')
                    <form action="{{route('products.store')}}" method="post">
                        {{ csrf_field() }}
                        <div class="form-body">
                            <div class="row p-t-20">

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Detalle</label>
                                        <input type="text" name='name' id="name" class="form-control form-control-danger" placeholder="Auriculares Sony" required>
                                        <small class="form-control-feedback"> Nombre del Producto. </small> </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Codigo</label>
                                        <input type="text" name='code' id="code" class="form-control" placeholder="113327" required>
                                        <small class="form-control-feedback"> Codigo del Producto</small> </div>
                                </div>

                            </div>
                            <div class="row">

                                <div class="col-md-6">
                                    <div class="form-group has-success">
                                        <label class="control-label">Existencias Iniciales</label>
                                        <input type="number" name="amount" class="form-control" placeholder="26" required>
                                        <small class="form-control-feedback"> Cantidad en Stock </small> </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Precio</label>
                                        <input type="number" name="price" class="form-control" min="0.00" max="1000000.00" step="0.01" placeholder="10" required>
                                        <small class="form-control-feedback"> Precio por unidad (Para la venta) </small> </div>
                                </div>

                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>
                            <a href="{{ route('products.index') }}" class="btn btn-danger" data-dismiss="modal" >Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/panel/products/edit.blade.php
@extends('panel.layouts.panel')
@section('content')
<br>
  <div class="row">
      <div class="col-lg-12">
          <div class="card card-outline-info">
              <div class="card-header">
                  <h4 class="m-b-0 text-white text-center">Editar producto</h4>
              </div>
              <div class="card-body">
                  @include('vendor.errors')
                  <form action="{{route('products.update', ['id' => $product->id])}}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT')}}
                      <div class="form-body">
                          <div class="row p-t-20">

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Detalle</label>
                                    <input type="text" name='name' id="name" class="form-control form-control-danger" value="{{$product->name}}" placeholder="Auriculares Sony" required>
                                    <small class="form-control-feedback"> Nombre del Producto. </small> </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Codigo</label>
                                    <input type="text" name='code' id="code" class="form-control" value="{{$product->code}}" placeholder="113327" >
                                    <small class="form-control-feedback"> Codigo del Producto</small> </div>
                            </div>

                          </div>

                          <div class="row">
                              <div class="col-md-6">
                                  <div class="form-group">
                                      <label class="control-label">Existencias</label>
                                      <input type="number" name="amount" class="form-control" value="{{$product->amount}}" placeholder="26" required>
                                      <small class="form-control-feedback"> Cantidad en Stock </small> </div>
                              </div>

                              <div class="col-md-6">
                                  <div class="form-group">
                                    <label class="control-label">Precio</label>
                                    <input type="number" name="price" class="form-control" min="0.00" max="10000.00" step="0.01" placeholder="10" value="{{$product->price}}" required>
                                    <small class="form-control-feedback"> Precio por unidad (Para la venta) </small> </div>
                                  </div>
                              </div>

                          </div>


                      <div class="form-actions">
                          <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>
                          <a href="{{ route('products.index') }}" class="btn btn-danger" data-dismiss="modal" >Cancelar</a>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
@endsection

resources/views/panel/products/index.blade.php
@extends('panel.layouts.panel')
@section('content')

<div class="card">
  <div class="card-body">
    <ul class="nav nav-tabs customtab" role="tablist">
      <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#" role="tab"><span class="hidden-sm-up"><i class="ti-home"></i></span> <span class="hidden-xs-down">Productos</span></a> </li>
      <li class="nav-item"> <a class="nav-link" href="{{route('providers.index')}}"><span class="hidden-sm-up"><i class="ti-user"></i></span> <span class="hidden-xs-down">Proveedores</span></a> </li>
      <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#messages2" role="tab"><span class="hidden-sm-up"><i class="ti-email"></i></span> <span class="hidden-xs-down">Movimientos de Stock</span></a> </li>
    </ul>
  </div>
</div>

{{-- Main row --}}
<div class="row">

  {{--------------- Inventory list --------------}}
  <div class="col-sm-12 col-md-8">
    <div class="card card-outline-info">

      <div class="card-header">
        <h4 class="m-b-0 text-white text-center">Lista de productos</h4>
      </div>

      <div class="card-body">
        <div class="table-responsive m-t-40">
          <table id="myTable" class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th>Detalle</th>
                <th>Existencias</th>
                <th>Precio Unidad</th>
              </tr>
            </thead>
            <tbody>

              @foreach ($products as $product)

              <tr id="producto{{$product->id}}" data-toggle="modal" data-target="#infon{{$product->id}}" data-whatever="@mdo">
                <td>{{$product->code}}</td>
                <td>{{$product->name}}</td>
                <td>{{$product->amount}}</td>
                <td>{{$product->price}}</td>
              </tr>

              {{------------------ Modal -------------}}
              <div class="modal fade" id="infon{{$product->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" style="display: none;" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title" id="exampleModalLabel1">{{$product->name}} (#{{$product->code}})</h4>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    </div>
                    <div class="modal-body">
                      <p>Existencias: <b>{{$product->amount}}</b> </p>
                      <p>Precio: ${{$product->price}}</p>
                    </div>
                    <div class="modal-footer">
                      <form id="formdelete{{$product->id}}" action="{{route('products.destroy', ['id' => $product->id])}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('delete') }}
                      </form>
                      <button type="button" class="btn btn-danger btn-rounded" id="sa-eliminar{{$product->id}}">Borrar</button>
                      <a href="{{route('products.edit', ['id' => $product->id])}}" class="btn btn-primary btn-rounded">Editar</a>
                      <button type="button" class="btn btn-default btn-rounded" data-dismiss="modal">Aceptar</button>
                    </div>
                  </div>
                </div>
              </div>
              {{----------------------------------}}

              @endforeach
              {{-- @if (Auth::user()->business->products->count() == 0)
              <td colspan="4" style="text-align:center;">No se encontraron resultados</td>
              @endif --}}

            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
  {{-- ------------------------------- --}}

  {{-- -------- New product ---------- --}}
  <div class="col-sm-12 col-md-4">
    <div class="card card-outline-info">

      <div class="card-header">
        <h4 class="m-b-0 text-white text-center">Nuevo producto</h4>
      </div>

      <div class="card-body">
        @include('vendor.errors')
        <form action="{{route('products.store')}}" method="post">
          {{ csrf_field() }}

          <div class="form-group">
            <label class="control-label">Detalle</label>
            <input type="text" name='name' id="name" class="form-control form-control-danger" placeholder="Auriculares Sony" required>
            <small class="form-control-feedback"> Nombre del Producto. </small>
          </div>

          <div class="form-group">
            <label class="control-label">Codigo</label>
            <input type="text" name='code' id="code" class="form-control" placeholder="113327" required>
            <small class="form-control-feedback"> Codigo del Producto</small>
          </div>

          <div class="form-group">
            <label class="control-label">Existencias Iniciales</label>
            <input type="number" name="amount" class="form-control" placeholder="26" required>
            <small class="form-control-feedback"> Cantidad en Stock </small>
          </div>

          <div class="form-group">
            <label class="control-label">Precio</label>
            <input type="number" name="price" class="form-control" min="0.00" max="1000000.00" step="0.01" placeholder="10" required>
            <small class="form-control-feedback"> Precio por unidad (Para la venta) </small>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-success btn-block btn-rounded"> <i class="fa fa-check"></i> Guardar</button>
          </div>
        </form>
      </div>

    </div>
  </div>
  {{-- ------------------------------- --}}

</div>
{{-- main row --}}

@endsection

@section('scripts')
<script src="{{asset('assets/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<!-- start - This is for export functionality only -->
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<script>
  $(document).ready(function() {
    $('#myTable').DataTable({
      "language": {
        "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
      }
    });
  });
  ! function($) {
    "use strict";

    var SweetAlert = function() {};

    //examples
    SweetAlert.prototype.init = function() {
        @foreach($products as $product)
        $('#sa-eliminar{{$product->id}}').click(function() {
          swal({
            title: "¿Estás seguro?",
            text: "Eliminarás el producto '{{$product->name}}'",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "¡Borralo!",
            cancelButtonText: "Cancelar",
            closeOnConfirm: false
          }, function(e) {
            if (e) {
              swal("Eliminado", "El producto fue eliminado.", "success");

              $('#formdelete{{$product->id}}').submit();
              $("#producto{{$product->id}}").remove();
            } else {
              swal("Cancelado", "Tu producto está a salvo.", "success");
            }


          });
        });
        @endforeach





      },
      //init
      $.SweetAlert = new SweetAlert, $.SweetAlert.Constructor = SweetAlert
  }(window.jQuery),

  //initializing
  function($) {
    "use strict";
    $.SweetAlert.init()
  }(window.jQuery);
</script>
<script src="{{asset('assets/plugins/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('assets/plugins/sweetalert/jquery.sweet-alert.custom.js')}}"></script>

@endsection

resources/views/panel/products/show.blade.php
@extends('panel.layouts.panel')
@section('content')

<h3>{{$product->name}}</h3>
<a class="btn btn-danger" href="{{route('products.edit', ['id' => $product->id])}}"> Editar </a>
@endsection