routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('panel');
});

Route::get('/prueba', function () {
    $user = Auth::user()->with('business')->with('business.entries')->first();
    return dd($user);
})->name('prueba');
Route::post('buscar', 'HomeController@buscar')->name('buscar');
Auth::routes(['register' => false]);

Route::prefix('panel')->group(function () {
    Route::get('/', 'HomeController@index')->name('panel');
    Route::get('account', 'HomeController@account')->name('settings');
    Route::post('changeuser/{user}', 'HomeController@changeuser')->name('changeuser');
    Route::post('changebiz/{business}', 'HomeController@changebiz')->name('changebiz');
    Route::resource('users', 'UserController');
    Route::resource('sales', 'SalesController');
    Route::resource('clients', 'ClientController');
    Route::resource('entries', 'EntryController');
    Route::resource('products', 'ProductsController');
    Route::resource('providers', 'ProvidersController');
    Route::resource('items', 'ProvidersItemController');
});

Route::prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('users', 'AdminController@userIndex')->name('admin.users.index');

});

app/Entry.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    protected $fillable = ['business_id', 'client_id', 'type', 'notes', 'status', 'final_price', 'pagado', 'marca', 'modelo', 'serie', 'notas'];

    // @return App/User model.
    public function business()
    {
      return $this->belongsTo('App\Business');
    }
    public function client()
    {
      return $this->belongsTo('App\Client');
    }
}

app/Http/Controllers/EntryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entry;
use App\Http\Requests\EntryStoreRequest;
use Auth;

class EntryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
         $this->middleware(['auth']);
    }

    public function index()
    {
        /*$subscription = Auth::user()->business->activeSubscription();
        if (Auth::user()->business->entries->count() < $subscription->features()->code('entries.amount')->first()->limit) {
            $entries = Auth::user()->business->entries()->orderBy('id', 'desc')->get();
            return view('panel.entries.index', compact('entries'));
        }
        else {
            return redirect()->back()->with('warning', 'Alcanzaste el limite de ordenes en tu plan.');
        }*/
        $entries = Auth::user()->business->entries()->orderBy('id', 'desc')->get();
        return view('panel.entries.index', compact('entries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('panel.entries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EntryStoreRequest $request)
    {
        $request->merge(['business_id' => auth()->user()->business->id]);
        Entry::create($request->all());
        return redirect('panel/entries')->with('message', 'Se creó una nueva entrada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $entry = Auth::user()->business->entries->find($id);
        return view('panel.entries.show', compact('entry'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entry = Auth::user()->business->entries->find($id);
        return view('panel.entries.edit', compact('entry', 'item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EntryStoreRequest $request, $id)
    {
        $request->merge(['business_id' => auth()->user()->business->id]);
        $entry = Auth::user()->business->entries->find($id);
        $entry->update($request->all());

        return redirect('panel')->with('message', 'Se editó una nueva entrada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/panel/entries/create.blade.php
@extends('panel.layouts.panel')
@section('content')
<br>
  <div class="row">
      <div class="col-lg-12">
          <div class="card card-outline-info">
              <div class="card-header">
                  <h4 class="m-b-0 text-white">Crear nueva Entrada</h4>
              </div>
              <div class="card-body">
                  @include('vendor.errors')
                  <form action="{{route('entries.store')}}" method="post">
                    {{ csrf_field() }}
                      <div class="form-body">

                        <h3 class="card-title">Cliente</h3>
                        <hr>
                        <div class="row">
                            <div class="col-md-6">
                              <center><label class="control-label">Si el cliente ya esta registrado en la base de datos</label>
                              <select class="select2" name="client_id" style="width: 100%" required>
                                  <optgroup label="Clientes disponibles">
                                    @foreach (Auth::user()->business->clients as $clients)
                                      <option value="{{$clients->id}}">{{$clients->id}} - {{$clients->name}} ({{$clients->email}})</option>
                                    @endforeach

                                  </optgroup>

                              </select></center>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                  <center><label class="control-label">Si el cliente es nuevo debe registrarlo</label><br></center>
                                  <center><a class="btn btn-rounded btn-success" href="{{route('clients.create')}}"><b style="color:white;">NUEVO CLIENTE</b></a></center>
                                </div>
                              </div>
                          </div>



                          <!--/row-->
                          <h3 class="box-title m-t-40">Equipo</h3>
                          <hr>
                          <div class="row">
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Marca <small>(Ejemplo: Samsung)</small> </label>
                                      <input type="text" name="marca" class="form-control" required>
                                  </div>
                              </div>
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Modelo <small>(Ejemplo: S8 Edge)</small> </label>
                                      <input type="text" name="modelo" class="form-control" required>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-md-12">
                                  <div class="form-group">
                                      <label>Serie <small>(IMEI u otro Identificador)</small></label>
                                      <input type="text" name="serie" class="form-control" required>
                                  </div>
                              </div>

                          </div>
                          <div class="row">
                            <div class="col-md-12">
                              <div class="form-group">
                                <label class="control-label">Detalles del equipo <small>(Describa las fallas del equipo)</small> </label>
                                <textarea name="notas" rows="2" cols="80" class="form-control" required></textarea>
                              </div>
                            </div>
                          </div>
                          <h3 class="box-title m-t-40">Orden</h3>
                          <hr>
                          <div class="row">
                            <div class="col-md-12">
                              <div class="form-group">
                                <label class="control-label">Notas para el cliente <small>(Estas notas aparecerán en la orden de trabajo)</small> </label>
                                <textarea name="notes" rows="2" cols="80" class="form-control"></textarea>
                              </div>
                            </div>
                          </div>
                          <div class="row">
                              <div class="col-md-6">
                                  <div class="form-group">
                                      <label class="control-label">Tipo de Orden</label>
                                      <select class="form-control custom-select" name='type' data-placeholder="Elija un tipo" tabindex="1" required>
                                          <option value="1">Presupuesto</option>
                                          <option value="2">Reparación</option>
                                          <option value="3">Garantía</option>
                                      </select>
                                  </div>
                              </div>
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Estado</label>
                                      <select class="form-control custom-select" name='status' data-placeholder="Elija un estado" tabindex="1" required>
                                          <option value="0">Pendiente</option>
                                          <option value="1">Finalizado</option>
                                          <option value="2">Entregado</option>
                                          <option value="3">Cancelado</option>
                                      </select>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Precio FINAL</label>
                                      <input type="number" name="final_price" step="0.01" class="form-control" required>
                                  </div>
                              </div>
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Seña/Pagado <small>(Si el cliente pago parte del monto final)</small> </label>
                                      <input type="number" name="pagado" step="0.01" class="form-control" value="0" required>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="form-actions">
                          <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>
                          <a href="{{ route('entries.index') }}" class="btn btn-danger" data-dismiss="modal" >Cancelar</a>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
@endsection

resources/views/panel/entries/edit.blade.php
@extends('panel.layouts.panel')
@section('content')
<br>
  <div class="row">
      <div class="col-lg-12">
          <div class="card card-outline-info">
              <div class="card-header">
                  <h4 class="m-b-0 text-white">Editar Entrada</h4>
              </div>
              <div class="card-body">
                  @include('vendor.errors')
                  <form action="{{route('entries.update', ['id' => $entry->id])}}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT')}}
                      <div class="form-body">

                        <h3 class="card-title">Cliente</h3>
                        <hr>
                        <div class="row">
                            <div class="col-md-6">
                              <center><label class="control-label">Si el cliente ya esta registrado en la base de datos</label>
                              <select class="select2" name="client_id" style="width: 100%" required>
                                  <option value="" disabled selected>Seleccione un cliente</option>
                                  <optgroup label="Clientes disponibles">
                                    @foreach (Auth::user()->business->clients as $clients)
                                      <option value="{{$clients->id}}" @if ($entry->client_id == $clients->id) selected @endif >{{$clients->id}} - {{$clients->name}} ({{$clients->email}})</option>
                                    @endforeach

                                  </optgroup>

                              </select></center>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                  <center><label class="control-label">Si el cliente es nuevo debe registrarlo</label><br></center>
                                  <center><a class="btn btn-rounded btn-success" href="{{route('clients.create')}}"><b style="color:white;">NUEVO CLIENTE</b></a></center>
                                </div>
                              </div>
                          </div>



                          <!--/row-->
                          <h3 class="box-title m-t-40">Equipo</h3>
                          <hr>
                          <div class="row">
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Marca</label>
                                      <input type="text" name="marca" class="form-control" value="{{$entry->marca}}" required>
                                  </div>
                              </div>
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Modelo</label>
                                      <input type="text" name="modelo" class="form-control" value="{{$entry->modelo}}" required>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-md-12">
                                  <div class="form-group">
                                      <label>Serie (IMEI u Otro Identificador)</label>
                                      <input type="text" name="serie" class="form-control" value="{{$entry->serie}}" required>
                                  </div>
                              </div>

                          </div>
                          <div class="row">
                            <div class="col-md-12">
                              <div class="form-group">
                                <label class="control-label">Detalles del equipo</label>
                                <textarea name="notas" rows="8" cols="80" class="form-control" required>{{$entry->notas}}</textarea>
                              </div>
                            </div>
                          </div>
                          <h3 class="box-title m-t-40">Orden</h3>
                          <hr>
                          <div class="row">
                            <div class="col-md-12">
                              <div class="form-group">
                                <label class="control-label">Anotaciones</label>
                                <textarea name="notes" rows="8" cols="80" class="form-control" required>{{$entry->notes}}</textarea>
                              </div>
                            </div>
                          </div>
                          <div class="row">
                              <div class="col-md-6">
                                  <div class="form-group">
                                      <label class="control-label">Tipo de Orden</label>
                                      <select class="form-control custom-select" name='type' data-placeholder="Elija un tipo" tabindex="1" required>
                                        <option value="1" @if ($entry->type == 1) selected @endif>Presupuesto</option>
                                        <option value="2" @if ($entry->type == 2) selected @endif>Reparación</option>
                                        <option value="3" @if ($entry->type == 3) selected @endif>Garantía</option>
                                      </select>
                                  </div>
                              </div>
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Estado</label>
                                      <select class="form-control custom-select" name='status' data-placeholder="Elija un estado" tabindex="1" required>
                                        <option value="0" @if ($entry->status == 0) selected @endif>Pendiente</option>
                                        <option value="1" @if ($entry->status == 1) selected @endif>Finalizado</option>
                                        <option value="2" @if ($entry->status == 2) selected @endif>Entregado</option>
                                        <option value="3" @if ($entry->status == 3) selected @endif>Cancelado</option>
                                      </select>
                                  </div>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Precio FINAL</label>
                                      <input type="number" value="{{$entry->final_price}}" name="final_price" class="form-control" required>
                                  </div>
                              </div>
                              <div class="col-md-6 ">
                                  <div class="form-group">
                                      <label>Seña/Pagado</label>
                                      <input type="number" value="{{$entry->pagado}}" name="pagado" class="form-control" required>
                                  </div>
                              </div>
                          </div>
                      </div>
                      <div class="form-actions">
                          <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>
                          <a href="{{ route('entries.index') }}" class="btn btn-danger" data-dismiss="modal" >Cancelar</a>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
@endsection

resources/views/panel/entries/show.blade.php
@extends('panel.layouts.panel')
@section('content')
<br>
  <div class="row" id="printableArea">
      <div class="col-md-12">

          <div class="card card-body printableArea">
              <h3><b>ORDEN DE TRABAJO   @if ($entry->status == 0)
                  <span class="label label-info">PENDIENTE</span>
                @elseif ($entry->status == 1)
                  <span class="label label-success">A ENTREGAR (Finalizado)</span>
                @elseif ($entry->status == 2)
                  <span class="label label-success">ENTREGADA</span>
                @elseif ($entry->status == 3)
                  <span class="label label-danger">CANCELADA</span>
              @endif</b> <span class="pull-right">#{{$entry->id}}</span></h3>
              <hr>
              <div class="row">
                  <div class="col-md-12">
                      <div class="pull-left">
                          <address>
                              <h3> &nbsp;<b class="text-danger">{{Auth::user()->business->name}}</b></h3>
                              <p class="text-muted m-l-5">{{Auth::user()->business->address}}
                                  <br/> {{Auth::user()->business->city}} ({{Auth::user()->business->cp}})
                                  <br/> {{Auth::user()->business->province}}
                                  <br/> Tel.: {{Auth::user()->business->phone}}</p>
                          </address>
                      </div>
                      <div class="pull-right text-right">
                          <address>
                              <h3>Para,</h3>
                              <h4 class="font-bold">{{$entry->client->name}}</h4>
                              <p class="text-muted m-l-30">{{$entry->client->address}}
                                  <br/> Tel.: {{$entry->client->phone}}</p>
                              <p class="m-t-30"><b>Fecha de emisión :</b> <i class="fa fa-calendar"></i> {{$entry->created_at}}</p>
                          </address>
                      </div>
                  </div>
                  <div class="col-md-6">
                      <p>{{$entry->marca}} {{$entry->modelo}} (@if ($entry->type == 1)
                        Presupuesto
                      @elseif ($entry->type == 2)
                        Reparación
                      @elseif ($entry->type == 3)
                        Garantía
                      @endif)</p>
                      <p>Serie: {{$entry->serie}}</p>
                      <hr>
                      <p> <b>Detalles del equipo:</b> {{$entry->notas}} </p>
                      <p> <b>Anotaciones:</b> {{$entry->notes}} </p>
                      <p>Precio: {{$entry->final_price}}</p>
                  </div>

                  <div class="col-md-12">
                      <div class="pull-right m-t-30 text-right">
                          <p>Sub - Total: ${{$entry->final_price}}</p>
                          <p>Pagado : ${{$entry->pagado}} </p>
                          <hr>
                          <h3><b>Total :</b> ${{$entry->final_price-$entry->pagado}}</h3>
                      </div>
                      <div class="clearfix"></div>
                      <hr>
                      <center><p>Si pasado los 30 dias de la presente, el aparato no fuera retirado, quedará en propiedad de este service, entendido que el titular renuncia al mismo de acuerdo a lo estipulado en los Art. 872 y 873 del Código Civil. En cumplimiento de Normas Legales Vigentes, me hago cargo responsable de haber dejado en reparación al aparato descripto.</p></center>
                      <div class="pull-left m-t-10 text-left">
                        <center><br>
                        <hr>
                      <b>--------Firma--------</b></center>
                      </div>

                      <div class="pull-right m-t-10 text-center">
                        <center><br>
                        <hr>
                      <b>--------DNI--------</b></center>
                      </div>
                  </div>



              </div>
          </div>
      </div>
  </div>
  <div class="clearfix"></div>
  <hr>
  <div class="card card-body">
    <div class="text-right">
        <a class="btn btn-danger" href="{{route('entries.edit', ['id' => $entry->id])}}"> Editar </a>
        <button onclick="printDiv('printableArea')" class="btn btn-default btn-outline" type="button"> <span><i class="fa fa-print"></i> Imprimir</span> </button>
    </div>
  </div>

@endsection