routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('panel');
});

Route::get('/prueba', function () {
    $user = Auth::user()->with('business')->with('business.entries')->first();
    return dd($user);
})->name('prueba');
Route::post('buscar', 'HomeController@buscar')->name('buscar');
Auth::routes(['register' => false]);

Route::prefix('panel')->group(function () {
    Route::get('/', 'HomeController@index')->name('panel');
    Route::get('account', 'HomeController@account')->name('settings');
    Route::post('changeuser/{user}', 'HomeController@changeuser')->name('changeuser');
    Route::post('changebiz/{business}', 'HomeController@changebiz')->name('changebiz');
    Route::resource('users', 'UserController');
    Route::resource('sales', 'SalesController');
    Route::resource('clients', 'ClientController');
    Route::resource('entries', 'EntryController');
    Route::resource('products', 'ProductsController');
    Route::resource('providers', 'ProvidersController');
    Route::resource('items', 'ProvidersItemController');
});

Route::prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
    Route::get('users', 'AdminController@userIndex')->name('admin.users.index');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'address', 'phone', 'group_id', 'state', 'business_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function business()
    {
      return $this->belongsTo('App\Business');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Auth;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'owner']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = Auth::user()->business->users->where('id', '!=', Auth::user()->id);
        return view('panel.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subscription = Auth::user()->business->activeSubscription();
        if (Auth::user()->business->users->count() < $subscription->features()->code('users.amount')->first()->limit) {
            return view('panel.users.create');
        }
        else {
            return redirect()->back()->with('warning', 'Alcanzaste el limite de usuarios en tu plan.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required',
            'address' => 'required',
            'password' => 'required|max:128',
        ]);
        $subscription = Auth::user()->business->activeSubscription();
        if (Auth::user()->business->users->count() < $subscription->features()->code('entries.amount')->first()->limit) {
            $createduser = User::create([
              'first_name' => $request->first_name,
              'last_name' => $request->last_name,
              'email' => $request->email,
              'phone' => $request->phone,
              'address' > $request->address,
              'password' => bcrypt($request->password),
              'business_id' => Auth::user()->business->id,
            ]);
            return redirect(route('users.index'))->with('message', 'Creaste un nuevo usuario');
        }
        else {
            return redirect()->back()->with('warning', 'Alcanzaste el limite de usuarios en tu plan.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('panel.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'phone' => 'required',
            'address' => 'required',
            'password' => 'required|max:128',
        ]);
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->email = $request->email;
        $user->address = $request->address;
        $user->phone = $request->phone;
        if ($request->password != null) {
          $user->password = bcrypt($request->newpassword);
        }
        $user->save();

        return redirect(route('users.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if ($user->id == Auth::user()->id) {
            return back()->with('warning', 'No puedes borrar tu cuenta');
        }
        if ($user->business->id != Auth::user()->business->id) {
            return back()->with('warning', 'No puedes borrar esta cuenta');
        }
        $user->delete();
        return back()->with('message', 'Se ha eliminado el usuario');
    }
}

resources/views/admin/users/index.blade.php
@extends('admin.layouts.admin')
@section('content')
  @php
    $users = App\User::where('group_id', '2')->get();
  @endphp
  <div class="card">
      <div class="card-body">
        <center><h4 class="card-title">Lista de Usuarios</h4></center>
        <center><h6 class="card-subtitle">Si usted desea crear un nuevo usuario haga <a href="{{route('users.create')}}">click aquí</a>.</h6></center>
          <div class="table-responsive m-t-40">
              <table id="myTable" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($users as $user)


                      <tr id="user{{$user->id}}" data-toggle="modal" data-target="#infou{{$user->id}}" data-whatever="@mdo">
                          <td>{{$user->id}}</td>
                          <td>{{$user->first_name}}</td>
                          <td>{{$user->last_name}}</td>
                          <td>{{$user->email}}</td>
                      </tr>
                      <div class="modal fade" id="infou{{$user->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" style="display: none;" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title" id="exampleModalLabel1">{{$user->first_name}} {{$user->last_name}} (#{{$user->id}})</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Nombre y Apellido: <b>{{$user->first_name}} {{$user->last_name}}</b> </p>
                                                <p>Email: {{$user->email}}</p>
                                                <p>Teléfono: {{$user->phone}}</p>
                                            </div>
                                            <div class="modal-footer">
                                              <form id="formdelete{{$user->id}}" action="{{route('users.destroy', ['user' => $user])}}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('delete') }}
                                              </form>
                                                <button type="button" class="btn btn-danger" id="sa-eliminar{{$user->id}}">Borrar</button>
                                                <a href="{{route('users.edit', ['user' => $user])}}" class="btn btn-primary">Editar</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                    @endforeach
                    @if (App\User::where('group_id', '2')->count() == 0)
                      <td></td>
                        <td>No se encontraron resultados</td>

                    @endif
                  </tbody>
              </table>
          </div>
      </div>
  </div>

@endsection

@section('scripts')
  <script src="{{asset('assets/plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <!-- start - This is for export functionality only -->
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
  <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
  <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
  <script>
  $(document).ready(function() {
      $('#myTable').DataTable();
      });
      !function($) {
          "use strict";

          var SweetAlert = function() {};

          //examples
          SweetAlert.prototype.init = function() {
          @foreach ($users as $user)
          $('#sa-eliminar{{$user->id}}').click(function(){
              swal({
                  title: "¿Estás seguro?",
                  text: "Eliminarás el usuario '{{$user->first_name}} {{$user->last_name}}'",
                  type: "warning",
                  showCancelButton: true,
                  confirmButtonColor: "#DD6B55",
                  confirmButtonText: "¡Borralo!",
                  cancelButtonText: "Cancelar",
                  closeOnConfirm: false
              }, function(e){
                if (e) {
                  swal("Eliminado", "El usuario fue eliminado.", "success");

                  $('#formdelete{{$user->id}}').submit();
                  $("#user{{$user->id}}").remove();
                }
                else {
                  swal("Cancelado", "Tu usuario está a salvo.", "success");
                }


              });
          });
          @endforeach





          },
          //init
          $.SweetAlert = new SweetAlert, $.SweetAlert.Constructor = SweetAlert
      }(window.jQuery),

      //initializing
      function($) {
          "use strict";
          $.SweetAlert.init()
      }(window.jQuery);
  </script>
  <script src="{{asset('assets/plugins/sweetalert/sweetalert.min.js')}}"></script>
  <script src="{{asset('assets/plugins/sweetalert/jquery.sweet-alert.custom.js')}}"></script>

@endsection